# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL_v2/Frequency-comb-DPLL-DPLL-python3/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii.xci
# IP: The module: 'pll_32x32_mult_ii' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL_v2/Frequency-comb-DPLL-DPLL-python3/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_32x32_mult_ii'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL_v2/Frequency-comb-DPLL-DPLL-python3/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii.xci
# IP: The module: 'pll_32x32_mult_ii' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL_v2/Frequency-comb-DPLL-DPLL-python3/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_32x32_mult_ii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
