# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/Ref_generator_DDS/Ref_generator_DDS.xci
# IP: The module: 'Ref_generator_DDS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/Ref_generator_DDS/Ref_generator_DDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ref_generator_DDS'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/Ref_generator_DDS/Ref_generator_DDS.xci
# IP: The module: 'Ref_generator_DDS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/Ref_generator_DDS/Ref_generator_DDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ref_generator_DDS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
