# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL_v2/Frequency-comb-DPLL-DPLL-python3/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/input_multiplier/input_multiplier.xci
# IP: The module: 'input_multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL_v2/Frequency-comb-DPLL-DPLL-python3/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/input_multiplier/input_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_multiplier'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL_v2/Frequency-comb-DPLL-DPLL-python3/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/input_multiplier/input_multiplier.xci
# IP: The module: 'input_multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL_v2/Frequency-comb-DPLL-DPLL-python3/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/input_multiplier/input_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
