# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.cache/wt [current_project]
set_property parent.project_path D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits.xci
set_property used_in_implementation false [get_files -all d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits.dcp]
set_property is_locked true [get_files D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top angle_CORDIC_14bits -part xc7z010clg400-1 -mode out_of_context
rename_ref -prefix_all angle_CORDIC_14bits_
write_checkpoint -noxdef angle_CORDIC_14bits.dcp
catch { report_utilization -file angle_CORDIC_14bits_utilization_synth.rpt -pb angle_CORDIC_14bits_utilization_synth.pb }
if { [catch {
  file copy -force D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.runs/angle_CORDIC_14bits_synth_1/angle_CORDIC_14bits.dcp D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.ip_user_files/ip/angle_CORDIC_14bits]} {
  catch { 
    file copy -force D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits_stub.v D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.ip_user_files/ip/angle_CORDIC_14bits
  }
}

if {[file isdir D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.ip_user_files/ip/angle_CORDIC_14bits]} {
  catch { 
    file copy -force D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC_14bits/angle_CORDIC_14bits_stub.vhdl D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.ip_user_files/ip/angle_CORDIC_14bits
  }
}
