# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk.xci
# IP: The module: 'fir_compiler_minimumphase_N_times_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_minimumphase_N_times_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_minimumphase_N_times_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk.xci
# IP: The module: 'fir_compiler_minimumphase_N_times_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_minimumphase_N_times_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_minimumphase_N_times_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
