# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.xpr} [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip {{c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync.dcp}}]
set_property is_locked true [get_files {{c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync.xci}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top clk_10MHz_sync -part xc7z010clg400-1 -mode out_of_context
rename_ref -prefix_all clk_10MHz_sync_
write_checkpoint -noxdef clk_10MHz_sync.dcp
catch { report_utilization -file clk_10MHz_sync_utilization_synth.rpt -pb clk_10MHz_sync_utilization_synth.pb }
if { [catch {
  file copy -force {C:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.runs/clk_10MHz_sync_synth_1/clk_10MHz_sync.dcp} {c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync.dcp}
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub {c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub {c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim {c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim {c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir {C:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.ip_user_files/ip/clk_10MHz_sync}]} {
  catch { 
    file copy -force {{c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync_stub.v}} {C:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.ip_user_files/ip/clk_10MHz_sync}
  }
}

if {[file isdir {C:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.ip_user_files/ip/clk_10MHz_sync}]} {
  catch { 
    file copy -force {{c:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync_stub.vhdl}} {C:/Users/Alex/Documents/GitHub/OnlineVersion2/Firmware Vivado Project/redpitaya.ip_user_files/ip/clk_10MHz_sync}
  }
}
