# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.cache/wt [current_project]
set_property parent.project_path D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk.xci
set_property used_in_implementation false [get_files -all d:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk.dcp]
set_property is_locked true [get_files D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top fir_compiler_minimumphase_N_times_clk -part xc7z010clg400-1 -mode out_of_context
rename_ref -prefix_all fir_compiler_minimumphase_N_times_clk_
write_checkpoint -noxdef fir_compiler_minimumphase_N_times_clk.dcp
catch { report_utilization -file fir_compiler_minimumphase_N_times_clk_utilization_synth.rpt -pb fir_compiler_minimumphase_N_times_clk_utilization_synth.pb }
if { [catch {
  file copy -force D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.runs/fir_compiler_minimumphase_N_times_clk_synth_1/fir_compiler_minimumphase_N_times_clk.dcp D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.ip_user_files/ip/fir_compiler_minimumphase_N_times_clk]} {
  catch { 
    file copy -force D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_stub.v D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.ip_user_files/ip/fir_compiler_minimumphase_N_times_clk
  }
}

if {[file isdir D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.ip_user_files/ip/fir_compiler_minimumphase_N_times_clk]} {
  catch { 
    file copy -force D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_stub.vhdl D:/Projets_Xilinx/RedPitayaLink/fpga/project/redpitaya.ip_user_files/ip/fir_compiler_minimumphase_N_times_clk
  }
}
