# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult.xci
# IP: The module: 'system_identification_outputgain_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_identification_outputgain_mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult.xci
# IP: The module: 'system_identification_outputgain_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_identification_outputgain_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
