# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/sf_D/Projects/RedPitaya/fpga/project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult.xci
# IP: The module: 'system_identification_outputgain_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_D/Projects/RedPitaya/fpga/project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_identification_outputgain_mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/sf_D/Projects/RedPitaya/fpga/project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult.xci
# IP: The module: 'system_identification_outputgain_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_D/Projects/RedPitaya/fpga/project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_identification_outputgain_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
