# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/sf_D/Projects/RedPitaya/fpga/project/redpitaya.srcs/sources_1/ip/pll_18x32_mult_d/pll_18x32_mult_d.xci
# IP: The module: 'pll_18x32_mult_d' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_D/Projects/RedPitaya/fpga/project/redpitaya.srcs/sources_1/ip/pll_18x32_mult_d/pll_18x32_mult_d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_18x32_mult_d'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/sf_D/Projects/RedPitaya/fpga/project/redpitaya.srcs/sources_1/ip/pll_18x32_mult_d/pll_18x32_mult_d.xci
# IP: The module: 'pll_18x32_mult_d' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_D/Projects/RedPitaya/fpga/project/redpitaya.srcs/sources_1/ip/pll_18x32_mult_d/pll_18x32_mult_d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_18x32_mult_d'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
