# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed.xci
# IP: The module: 'FIFO_addr_packed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed/FIFO_addr_packed.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_addr_packed'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_addr_packed'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed.xci
# IP: The module: 'FIFO_addr_packed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed/FIFO_addr_packed.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_addr_packed'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_addr_packed'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
