# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.cache/wt [current_project]
set_property parent.project_path D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii.xci
set_property used_in_implementation false [get_files -all d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii.dcp]
set_property is_locked true [get_files D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top pll_32x32_mult_ii -part xc7z010clg400-1 -mode out_of_context
rename_ref -prefix_all pll_32x32_mult_ii_
write_checkpoint -noxdef pll_32x32_mult_ii.dcp
catch { report_utilization -file pll_32x32_mult_ii_utilization_synth.rpt -pb pll_32x32_mult_ii_utilization_synth.pb }
if { [catch {
  file copy -force D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.runs/pll_32x32_mult_ii_synth_1/pll_32x32_mult_ii.dcp D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.ip_user_files/ip/pll_32x32_mult_ii]} {
  catch { 
    file copy -force D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_stub.v D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.ip_user_files/ip/pll_32x32_mult_ii
  }
}

if {[file isdir D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.ip_user_files/ip/pll_32x32_mult_ii]} {
  catch { 
    file copy -force D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_stub.vhdl D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.ip_user_files/ip/pll_32x32_mult_ii
  }
}
