# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/Ref_generator_DDS_2/Ref_generator_DDS_2.xci
# IP: The module: 'Ref_generator_DDS_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/Ref_generator_DDS_2/Ref_generator_DDS_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ref_generator_DDS_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/Ref_generator_DDS_2/Ref_generator_DDS_2.xci
# IP: The module: 'Ref_generator_DDS_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/Ref_generator_DDS_2/Ref_generator_DDS_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ref_generator_DDS_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
