# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_wide_mult/pll_wide_mult.xci
# IP: The module: 'pll_wide_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_wide_mult/pll_wide_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_wide_mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_wide_mult/pll_wide_mult.xci
# IP: The module: 'pll_wide_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Alex/Documents/GitHub/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_wide_mult/pll_wide_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_wide_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
