# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC/angle_CORDIC.xci
# IP: The module: 'angle_CORDIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC/angle_CORDIC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'angle_CORDIC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC/angle_CORDIC.xci
# IP: The module: 'angle_CORDIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repo/Frequency-comb-DPLL/Firmware_Vivado_Project/redpitaya.srcs/sources_1/ip/angle_CORDIC/angle_CORDIC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'angle_CORDIC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
